server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://8.130.74.241:3306/cloud_user?useSSL=false
    username: root
    password: JJFJJmldhz
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.239.1:8848
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS